// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs0O7ZnBnuK4BHHePCmomvxmR-4QDE80g',
    appId: '1:446545585482:android:836273945322ea32f6cdb3',
    messagingSenderId: '446545585482',
    projectId: 'gaudiyamissionexam',
    storageBucket: 'gaudiyamissionexam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKhraVPoI91Zur2hxJm7pk8r4u_E9n3SU',
    appId: '1:446545585482:ios:9ee2cf5eb0410a44f6cdb3',
    messagingSenderId: '446545585482',
    projectId: 'gaudiyamissionexam',
    storageBucket: 'gaudiyamissionexam.firebasestorage.app',
    androidClientId: '446545585482-rn4h5s8cg8ptgltg0a5schrlin4n3n9r.apps.googleusercontent.com',
    iosClientId: '446545585482-16klroebbpvpm1c5qjeg84cu6qiflhqb.apps.googleusercontent.com',
    iosBundleId: 'com.gaudiyamission.exam',
  );

}